analysis_id: A59ae2d
name: ReCoHSI_glycoprofiling_Total_IgG
type: Glycoprofiling
study_ids: RCHSI
experiment_ids: Eae5e0d
analysis_ids: .na
table_dependecies: .na
publication_pmid: .na
description: .na
project_location: .na
source_ready: .na
git_repo: .na
owner: .na
protein_specific: yes
antigen_specific: no
antigen: ~
glycan_release: ~
software: LaCyTools
lacytools_version: 2.1.0
lacytools_build: 20230525
calib_mass_window: 0.1
calib_sn_cutoff: 27
calib_min_peak: 3
sum_spectrum_resolution: 100
mass_window: 0.05
time_window: 8
min_charge: 2
max_charge: 4
min_total: 0.95
background_window: 10
dependencies: []
