#' Generate R code for initializing codebook entries
#'
#' Reads the specified codebook and prints one assignment line per variable to
#' the console in the format `databook$data$<variable> <- <NA_type>`. Fields
#' that are auto-generated by the database (`script_id`, `participant_id`,
#' `event_id`) are skipped.
#'
#' @param codebook_name Character. The name of the codebook (without `.yaml` extension).
#' @return Invisibly returns `NULL`. Output is written to the console via `cat()`.
#' @seealso [codebookRead()], [codebookToSummary()]
#' @examples
#' \dontrun{
#'   codebookToDraft("participant")
#' }
#' @export
codebookToDraft <- function(codebook_name) {
  cb <- codebookRead(codebook_name=codebook_name)$variables

  # If the codebook was not found, throw an error
  if (is.null(cb)) {
    stop("Codebook '", codebook_name, "' not found. Run codebookToOverview() to get an overview of available codebooks.")
  }

  for (field_name in names(cb)) {
    # Skip field because we don't want to show them in the ETL script
    # These fields are automatically added in the database update
    fieldsToSkip <- c("script_id", "participant_id", "event_id")
    if (field_name %in% fieldsToSkip) {
      next
    }

    na_type <- .getNaType(cb[[field_name]]$type)

    # line <- if (codebook_name != "id_mapping") {
    #   sprintf(
    #     "databook$data$%s <- something special,
    #     field_name
    #   )
    # } else {
    line <- sprintf(
        "databook$data$%s <- %s",
        field_name,
        na_type
    )
    # }

    # }
    # Append this line to the output
    cat("#", field_name, "\n", line, "\n\n", sep="")
  }
}

#' @keywords internal
.getNaType <- function(type) {
  na_mapping <- list(
    "character" = "NA_character_",
    "numeric" = "NA_real_",
    "integer" = "NA_integer_"
  )

  if (!is.null(na_mapping[type])) {
    return(na_mapping[type])
  } else {
    warning(paste("Unknown type:", type))
    return("NA")
  }
}

