#' Prepare data from a `databook` for uploading to database
#'
#' Prepares the data contained in a `databook` object for upload and writes it
#' to the database. This includes adding the source ETL script `script_id` and,
#' when applicable, resolving `source_id` values to `participant_id` values and
#' `event_id` using the `id_mapping` table.
#'
#' @details
#' Special handling is applied depending on `databook$codebook_name`:
#'
#' - `"id_mapping"`: Adds a deterministic `participant_id` column via `.addParticipantIds()`.
#' - Other tables: If the data contains a `source_id` column, the function
#'   joins against the database `id_mapping` table to add `participant_id`.
#'   The `source_id` column is then set to `NA`.
#' - Other tables without `source_id`: if `participant_id` is already present
#'   in the data it is used directly; this is logged at `info` level.
#'
#' If the data is successfully uploaded to the database, `table_script`
#' is also updated with metadata for that `script_id`, including the MD5 hash
#' of the ETL script and the codebook version.
#'
#' @param databook A list as generated by [sourceScript()]. Must contain at
#'   least:
#'   - `$data`: A data frame with the table to upload.
#'   - `$codebook_name`: Character; target table name in the database.
#'   - `$codebook_version`: Character; version identifier for the codebook.
#' @param script_id Character. Both the identifier and file path of the ETL
#'   script; read to compute the MD5 hash.
#' @param con A DBI connection. If `NULL`, the default connection set by [FAIRgroundConnect()] is used.
#'
#' @return `TRUE` if data was successfully pushed and `table_script` updated,
#'   `FALSE` otherwise.
#'
#' @examples
#' \dontrun{
#' FAIRgroundConnect("LUCID_FAIRPOINT_TEST")
#' script_id <- "studies/LaCHMI/scripts/participant.R"
#' databook <- sourceScript(script_id = script_id)
#' databasePrepareData(databook, script_id = script_id)
#' }
#'
#' @export
databasePrepareData <- function(databook, script_id, con=NULL) {
  lg <- lgr::get_logger("beFAIR")
  con <- FAIRgroundConnection(con)

  lg$info("Preparing databook for upload to database",
          script_id = script_id,
          codebook_name = databook$codebook_name,
          codebook_version = databook$codebook_version)
  df <- databook$data

  # special case for "id_mapping"
  if (databook$codebook_name == "id_mapping") {
    df <- .addParticipantIds(df)
    df$script_id <- script_id

    pushed <- .sqlPushTable(con, data=df, databook$codebook_name, script_id=script_id)
    if(pushed){
      scriptHash <- .hash(paste(readLines(script_id, warn = FALSE), collapse = "\n"), type = "string",
                          algo = "md5")
      updated <- .updateTableScript(
        con,
        script_id,
        databook=databook
        )
    if(updated){
      return(TRUE)
    } else return(FALSE)
    } else {
      return(FALSE)
    }
  }

  # add participant_id and remove source_id
  if ("source_id" %in% names(df)) {

    skip_ids <- c(
      "BLANK", "STD", "CTRL",
      "NEG_CTRL", "POS_CTRL",
      "BLANK_STD", "SAMPLE_STD"
    )

    # check if it is a participant_id (eg.RCHSI_24as32)
    is_participant_id <- mapply(
      function(id, study) {
        grepl(paste0("^", study, "_[A-Za-z0-9]{6}$"), id)
      },
      df$source_id,
      df$study_id
    )

    df <- df %>%
      mutate(
        .is_skip = source_id %in% skip_ids,
        .is_participant = is_participant_id
      )

    skipped <- df$source_id[df$.is_skip]

    if (length(skipped) > 0) {
      lg$info(
        "Skipping reserved source IDs for event_id mapping; using source_id as participant_id",
        script_id = script_id,
        codebook_name = databook$codebook_name,
        skipped_ids = unique(skipped)
      )
    }

    # split logic: participant_id vs source_id
    id_map <- DBI::dbReadTable(con, "id_mapping") %>%
      dplyr::select(source_id, study_id, participant_id)

    df_source <- df %>%
      dplyr::filter(!.is_participant) %>%
      dplyr::select(-any_of("participant_id")) %>%
      dplyr::left_join(
        id_map,
        by = join_by(source_id, study_id)
      ) %>%
      dplyr::mutate(source_id = NA_character_)

    df_participant <- df %>%
      dplyr::filter(.is_participant) %>%
      dplyr::mutate(
        participant_id = source_id,
        source_id = NA_character_
      )

    # recombine
    dfMapped <- dplyr::bind_rows(df_source, df_participant)

    # event_id derivation
    if ("event_id" %in% names(dfMapped)) {

      if ("timepoint" %in% names(dfMapped)) {

        if (any(is.na(dfMapped$timepoint))) {
          lg$warn(
            "`timepoint contains NA, which will result in failed event_id mapping",
            script_id = script_id,
            codebook_name = databook$codebook_name
          )
        }

        dfMapped <- dfMapped %>%
          dplyr::mutate(
            event_id = paste0(
              participant_id,
              "_",
              sprintf("%04d", timepoint)
            ),
            event_id = if_else(.is_skip, NA_character_, event_id)
          ) %>%
          dplyr::relocate(event_id, .after = source_id)

      } else {
        lg$error(
          "timepoint is missing in codebook, cannot map source_id to event_id",
          script_id = script_id,
          codebook_name = databook$codebook_name
        )
      }
    }

  } else {

    # no source_id column present
    if ("participant_id" %in% names(df)) {
      lg$info(
        "Codebook has no 'source_id'; using 'participant_id' directly",
        script_id = script_id,
        codebook_name = databook$codebook_name,
        codebook_version = databook$codebook_version
      )
    }

    dfMapped <- df
  }

  dfMapped$script_id <- script_id

  dfMapped <- dfMapped %>%
    dplyr::select(-any_of(c(".is_skip", ".is_participant")))

  pushed <- .sqlPushTable(con, data=dfMapped, databook$codebook_name, script_id=script_id)
  if(pushed){
    scriptHash <- .hash(paste(readLines(script_id, warn = FALSE), collapse = "\n"), type = "string",
                        algo = "md5")
    updated <- .updateTableScript(
      con,
      script_id,
      databook=databook
    )
    if(updated){
      return(TRUE)
    } else return(FALSE)
  } else {
    return(FALSE)
  }
}





