#' Draft an ETL script for a study, experiment, or analysis
#'
#' Creates a template R script under the appropriate `scripts/` subfolder.
#' The DATA section is generated by [codebookToDraft()] from the variables
#' defined in the named codebook.
#'
#' @param name A character string specifying the name of the study,
#'   experiment, or analysis.
#' @param pillar A character string; one of `"studies"`, `"experiments"`,
#'   or `"analyses"`.
#' @param codebook_name A character string specifying the codebook name.
#' @param overwrite Logical. If `TRUE`, an existing script will be
#'   overwritten. Defaults to `FALSE`.
#'
#' @return Called for its side effects. Writes an R script and invisibly
#'   returns `NULL`.
#'
#' @seealso [codebookToDraft()], [codebookToSummary()]
#'
#' @examples
#' \dontrun{
#' draftScript("CoHSI1", "studies", "participant")
#' draftScript("NIH_CyTOF_exvivo", "analyses", "som_measurement")
#' }
#' @export
draftScript <- function(name, pillar, codebook_name, overwrite = FALSE) {
  pillar <- match.arg(tolower(pillar), c("studies", "experiments", "analyses"))

  if (is.null(codebook_name)) {
    stop("'codebook_name' is required.")
  }

  id_field <- switch(pillar,
    studies     = "study_id",
    experiments = "experiment_id",
    analyses    = "analysis_id"
  )
  id_var <- switch(pillar,
    studies     = "studyID",
    experiments = "experimentID",
    analyses    = "analysisID"
  )
  name_var <- switch(pillar,
    studies     = "studyName",
    experiments = "experimentName",
    analyses    = "analysisName"
  )

  pillar_dir <- pillar

  script_path <- file.path(pillar_dir, name, "scripts", paste0(codebook_name, ".R"))

  if (!overwrite && file.exists(script_path)) {
    stop(sprintf("'%s' already exists. Set overwrite=TRUE to overwrite.", script_path))
  }

  sink(file = script_path)
  cat(sep = "",
    '###\n## Dependencies\n#\n\n',
    '# meta.yaml\n',
    'metaFile <- paste0("', pillar_dir, '/', name, '/meta.yaml")\n',
    'metaInfo <- yaml::read_yaml(metaFile)\n',
    id_var, ' <- metaInfo$', id_field, '\n\n',
    name_var, ' <- metaInfo$name \n\n',
    '###\n## Load raw data\n#\n\n',
    '# !! write code to load the raw data !!\n\n',
    '###\n## Data preparation\n#\n\n',
    '# !! write code for specific data preparation !!\n\n',
    '###\n## DATABOOK\n#\n\n',
    'nEntries <- NA # !! Specify the number of rows in the final dataset !!\n',
    'databook <- beFAIR::codebookToEntries("', codebook_name, '", nrow = nEntries)\n\n',
    '###\n## DATA\n#\n'
  )
  codebookToDraft(codebook_name)
  cat(sep = "",
    '###\n## Validate entries\n#\n\n',
    'databook$validation <- beFAIR::validateDatabook(databook)\n\n',
    '###\n## Clean environment\n#\n',
    'rm(list = setdiff(ls(), c("databook")))\n'
  )
  sink()
}
